var theImages = new Array()

theImages[0] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/1.png'
theImages[1] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/2.png'
theImages[2] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/3.png'
theImages[3] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/4.png'
theImages[4] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/5.png'
theImages[5] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/6.png'
theImages[6] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/7.png'
theImages[7] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/8.png'
theImages[8] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/9.png'
theImages[9] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/10.png'
theImages[10] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/11.png'
theImages[11] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/12.png'
theImages[12] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/13.png'
theImages[13] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/14.png'
theImages[14] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/15.png'
theImages[15] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/16.png'
theImages[16] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/17.png'
//theImages[17] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/18.png'
//theImages[18] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/19.png'
//theImages[19] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/20.png'
//theImages[20] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/21.png'
//theImages[21] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/22.png'
//theImages[22] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/23.png'
//theImages[23] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/24.png'
//theImages[24] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/25.png'
//theImages[25] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/26.png'
//theImages[26] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/27.png'
//theImages[27] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/28.png'
//theImages[28] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/29.png'
//theImages[29] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/30.png'
//theImages[30] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/31.png'
//theImages[31] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/32.png'
//theImages[32] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/33.png'
//theImages[33] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/34.png'
//theImages[34] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/35.png'
//theImages[35] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/36.png'
//theImages[36] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/37.png'
//theImages[37] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/38.png'
//theImages[38] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/39.png'
//theImages[39] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/40.png'
//theImages[40] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/41.png'
//theImages[41] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/42.png'
//theImages[42] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/43.png'
//theImages[43] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/44.png'
//theImages[44] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/45.png'
//theImages[45] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/46.png'
//theImages[46] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/47.png'
//theImages[47] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/48.png'

var theEmbedCode = new Array()

theEmbedCode[0] = '3V35jvY0u7I'
theEmbedCode[1] = 'http://the-sleepiest-cloud.tumblr.com/'
theEmbedCode[2] = 'g_PoPIvKPe4'
theEmbedCode[3] = 'http://niceme.me/'
theEmbedCode[4] = '04jjf61FDNg'
theEmbedCode[5] = 'http://www.amazon.co.uk/registry/wishlist/1ZH4W2SP7ZBXH'
theEmbedCode[6] = 'n5KpeRt-LmY'
theEmbedCode[7] = 'suSSdHr8sog'
theEmbedCode[8] = 'http://i.imgur.com/5vzAWi2.gif'
theEmbedCode[9] = '3V35jvY0u7I'
theEmbedCode[10] = 'eQR1r1KTjaE'
theEmbedCode[11] = 'sPW9ki-IfZ8'
theEmbedCode[12] = 'T6CMZhkK7kU'
theEmbedCode[13] = 'jk2cGZPVW-g'
theEmbedCode[14] = 'QL4O8adW9_w'
theEmbedCode[15] = 'https://www.youtube.com/results?search_query=doge+meme'
theEmbedCode[16] = 'cqPD4A-bKNA'
theEmbedCode[17] = ''
theEmbedCode[18] = ''
theEmbedCode[19] = ''
theEmbedCode[20] = ''
theEmbedCode[21] = ''
theEmbedCode[22] = ''
theEmbedCode[23] = ''
theEmbedCode[24] = ''
theEmbedCode[25] = ''
theEmbedCode[26] = ''
theEmbedCode[27] = ''
theEmbedCode[28] = ''
theEmbedCode[29] = ''
theEmbedCode[30] = ''
theEmbedCode[31] = ''
theEmbedCode[32] = ''
theEmbedCode[33] = ''
theEmbedCode[34] = ''
theEmbedCode[35] = ''
theEmbedCode[36] = ''
theEmbedCode[37] = ''
theEmbedCode[38] = ''
theEmbedCode[39] = ''
theEmbedCode[40] = ''
theEmbedCode[41] = ''
theEmbedCode[42] = ''
theEmbedCode[43] = ''
theEmbedCode[44] = ''
theEmbedCode[45] = ''
theEmbedCode[46] = ''
theEmbedCode[47] = ''

var theExtras = new Array()

theExtras[0] = ''
theExtras[1] = ''
theExtras[2] = ''
theExtras[3] = ''
theExtras[4] = ''
theExtras[5] = ''
theExtras[6] = ''
theExtras[7] = ''
theExtras[8] = 'style="width: 100%;"'
theExtras[9] = '&start=93.2&end=96.4'
theExtras[10] = ''
theExtras[11] = ''
theExtras[12] = ''
theExtras[13] = ''
theExtras[14] = ''
theExtras[15] = ''
theExtras[16] = ''
theExtras[17] = ''
theExtras[18] = ''
theExtras[19] = ''
theExtras[20] = ''
theExtras[21] = ''
theExtras[22] = ''
theExtras[23] = ''
theExtras[24] = ''
theExtras[25] = ''
theExtras[26] = ''
theExtras[27] = ''
theExtras[28] = ''
theExtras[29] = ''
theExtras[30] = ''
theExtras[31] = ''
theExtras[32] = ''
theExtras[33] = ''
theExtras[34] = ''
theExtras[35] = ''
theExtras[36] = ''
theExtras[37] = ''
theExtras[38] = ''
theExtras[39] = ''
theExtras[40] = ''
theExtras[41] = ''
theExtras[42] = ''
theExtras[43] = ''
theExtras[44] = ''
theExtras[45] = ''
theExtras[46] = ''
theExtras[47] = ''


var theType = new Array()

theType[0] = 'RenderVideo()'
theType[1] = 'RenderLink()'
theType[2] = 'RenderVideo()'
theType[3] = 'RenderLink()'
theType[4] = 'RenderVideo()'
theType[5] = 'RenderLink()'
theType[6] = 'RenderVideo()'
theType[7] = 'RenderVideo()'
theType[8] = 'RenderImage()'
theType[9] = 'RenderVideo()'
theType[10] = 'RenderVideo()'
theType[11] = 'RenderVideo()'
theType[12] = 'RenderVideo()'
theType[13] = 'RenderVideo()'
theType[14] = 'RenderVideo()'
theType[15] = 'RenderLink()'
theType[16] = 'RenderVideo()'
theType[17] = ''
theType[18] = ''
theType[19] = ''
theType[20] = ''
theType[21] = ''
theType[22] = ''
theType[23] = ''
theType[24] = ''
theType[25] = ''
theType[26] = ''
theType[27] = ''
theType[28] = ''
theType[29] = ''
theType[30] = ''
theType[31] = ''
theType[32] = ''
theType[33] = ''
theType[34] = ''
theType[35] = ''
theType[36] = ''
theType[37] = ''
theType[38] = ''
theType[39] = ''
theType[40] = ''
theType[41] = ''
theType[42] = ''
theType[43] = ''
theType[44] = ''
theType[45] = ''
theType[46] = ''
theType[47] = ''


var j = 0
var p = theImages.length;

var preBuffer = new Array()
for (i = 0; i < p; i++){
   preBuffer[i] = new Image()
   preBuffer[i].src = theImages[i]
}
//it's rigged for now, for the purpose of testing
var whichImage = 16
    //Math.round(Math.random()*(p-1));

function showImage(){
    if (theType[whichImage]=='RenderLink()')
    {
    document.write('<a href="'+theEmbedCode[whichImage]+'"> <img src="'+theImages[whichImage]+'" class=avvy> </a>');
    }
    else
    {
    document.write('<img src="'+theImages[whichImage]+'" class="avvy" onclick="ShowStuff();pauseParallax();'+theType[whichImage]+'">');
    }
}

function RenderImage(){
document.getElementById("toggle").innerHTML = '<img src="'+theEmbedCode[whichImage]+'" '+theExtras[whichImage]+' >'
}
function RenderVideo(){
document.getElementById("toggle").innerHTML = '<object width="720" height="405"><param name="movie" value="https://www.youtube.com/v/'+theEmbedCode[whichImage]+'?autoplay=1&controls=0&disablekb=1&modestbranding=1&rel=0&showinfo=0&autohide=1&version=3"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><embed src="https://www.youtube.com/v/'+theEmbedCode[whichImage]+'?autoplay=1&controls=0&disablekb=1&iv_load_policy=3&modestbranding=1&rel=0'+theExtras[whichImage]+'&showinfo=0&autohide=1&version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="720" height="405"></embed></object>';
}

function DerenderVideo(){
    document.getElementById("toggle").innerHTML = "IGNOREME"
}
