var theImages = new Array()

theImages[0] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/1.png'
theImages[1] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/2.png'
theImages[2] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/3.png'
theImages[3] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/4.png'
theImages[4] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/5.png'
theImages[5] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/6.png'
theImages[6] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/7.png'
theImages[7] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/8.png'
theImages[8] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/9.png'
theImages[9] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/10.png'
theImages[10] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/11.png'
theImages[11] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/12.png'
theImages[12] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/13.png'
theImages[13] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/14.png'
theImages[14] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/15.png'
theImages[15] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/16.png'
theImages[16] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/17.png'
theImages[17] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/18.png'
theImages[18] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/19.png'
theImages[19] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/20.png'
theImages[20] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/21.png'
theImages[21] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/22.png'
theImages[22] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/23.png'
theImages[23] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/24.png'
theImages[24] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/25.png'
theImages[25] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/26.png'
theImages[26] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/27.png'
theImages[27] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/28.png'
theImages[28] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/29.png'
theImages[29] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/30.png'
theImages[30] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/31.png'
theImages[31] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/32.png'
theImages[32] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/33.png'
theImages[33] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/34.png'
theImages[34] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/35.png'
theImages[35] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/36.png'
theImages[36] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/37.png'
theImages[37] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/38.png'
theImages[38] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/39.png'
theImages[39] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/40.png'
theImages[40] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/41.png'
theImages[41] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/42.png'
theImages[42] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/43.png'
theImages[43] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/44.png'
theImages[44] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/45.png'
theImages[45] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/46.png'
theImages[46] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/47.png'
theImages[47] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/Avvys/48.png'


var theLinks = new Array()

theLinks[0] = 'https://www.youtube.com/watch?v=3V35jvY0u7I'
theLinks[1] = 'http://the-sleepiest-cloud.tumblr.com/'
theLinks[2] = 'https://www.youtube.com/watch?v=g_PoPIvKPe4'
theLinks[3] = 'http://niceme.me/'
theLinks[4] = 'https://www.youtube.com/watch?v=04jjf61FDNg'
theLinks[5] = 'http://www.amazon.co.uk/registry/wishlist/1ZH4W2SP7ZBXH'
theLinks[6] = 'https://www.youtube.com/watch?v=3zC-OyzIyVE'
theLinks[7] = 'https://www.youtube.com/watch?v=suSSdHr8sog'
theLinks[8] = 'http://i.imgur.com/5vzAWi2.gif'
theLinks[9] = 'https://www.youtube.com/watch?v=3V35jvY0u7I#t=95'
theLinks[10] = 'https://www.youtube.com/watch?v=eQR1r1KTjaE'
theLinks[11] = 'https://www.youtube.com/watch?v=sPW9ki-IfZ8'
theLinks[12] = 'https://www.youtube.com/watch?v=T6CMZhkK7kU'
theLinks[13] = 'https://www.youtube.com/watch?v=jk2cGZPVW-g'
theLinks[14] = 'https://www.youtube.com/watch?v=QL4O8adW9_w'
theLinks[15] = 'https://www.youtube.com/results?search_query=doge+meme'
theLinks[16] = 'https://www.youtube.com/watch?v=cqPD4A-bKNA'
theLinks[17] = 'https://www.youtube.com/watch?v=feCXr86HzMk'
theLinks[18] = 'https://www.youtube.com/watch?v=PS3jlUPPf5U'
theLinks[19] = 'https://www.youtube.com/watch?v=PYtXuBN1Hvc'
theLinks[20] = 'https://www.youtube.com/watch?v=OUXnHNb2zd0'
theLinks[21] = 'https://www.youtube.com/watch?v=7pKXIBYmI0w'
theLinks[22] = 'https://www.youtube.com/watch?v=izUYuvsMfoQ'
theLinks[23] = 'https://www.youtube.com/watch?v=Djr4jfHcslA'
theLinks[24] = 'https://www.youtube.com/watch?v=EjH9cEoEup8#t=75'
theLinks[25] = 'https://www.youtube.com/watch?v=dE-IoRk1qgk'
theLinks[26] = 'http://i.imgur.com/C4idW6A.jpg'
theLinks[27] = 'https://www.youtube.com/watch?v=iDbyYGrswtg'
theLinks[28] = 'https://www.youtube.com/watch?v=7ZRcsoyu6Tg'
theLinks[29] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/CodeMonkey.swf'
theLinks[30] = 'https://www.youtube.com/embed/tXjtATYG72w?autoplay=1&rel=0'
theLinks[31] = 'https://www.youtube.com/embed/OlRgazC3UAE?autoplay=1&rel=0'
theLinks[32] = 'https://www.youtube.com/watch?v=8GFnOGPGoOA'
theLinks[33] = 'https://www.youtube.com/watch?v=PSYxT9GM0fQ'
theLinks[34] = 'https://www.youtube.com/watch?v=VX6KjdeI6KU'
theLinks[35] = 'https://www.youtube.com/watch?v=d7r9RqWBdl8'
theLinks[36] = 'https://www.youtube.com/watch?v=u9ymUX1fJLw'
theLinks[37] = 'https://www.youtube.com/watch?v=yzbQ_h_uuVc'
theLinks[38] = 'http://i.imgur.com/RkbAGFE.jpg'
theLinks[39] = 'https://www.youtube.com/watch?v=utaWZT5N-tQ'
theLinks[40] = 'https://www.youtube.com/watch?v=sJeBTCzILzw'
theLinks[41] = 'https://www.youtube.com/watch?v=aboZctrHfK8'
theLinks[42] = 'http://rainbowdashalwaysdressesinstyle.com/Tumblr/8993.gif'
theLinks[43] = 'https://www.youtube.com/watch?v=QwIDiJ_zd_k'
theLinks[44] = 'https://www.youtube.com/embed/b1smWr5xrS8?autoplay=1&rel=0&start=5&end=13'
theLinks[45] = 'https://www.youtube.com/embed/TKJLd_cQ068?autoplay=1&rel=0&start=5&end=38'
theLinks[46] = 'https://www.youtube.com/embed/W9DST-6jIBU?autoplay=1&rel=0&start=183&end=189'
theLinks[47] = 'https://www.youtube.com/embed/iEIlxdPXJUY?autoplay=1&rel=0&start=11&end=34'


var j = 0
var p = theImages.length;
 
var preBuffer = new Array()
for (i = 0; i < p; i++){
   preBuffer[i] = new Image()
   preBuffer[i].src = theImages[i]
}

var whichImage = Math.round(Math.random()*(p-1));
function showImage(){
document.write('<a href="'+theLinks[whichImage]+'"> <img src="'+theImages[whichImage]+'" class=avvy> </a>');
}
